# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: M-x codefalling
subtitle:
description:
author: codefalling
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://codefalling.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: clean

# Deployment
## Docs: http://hexo.io/docs/deployment.html
#deploy:
#  type: git
#  repo:
#  branch: master
#  repo:
#    github: https://github.com/CodeFalling/codefalling.github.io,master
#    #gitcafe: git@gitcafe.com:falling/falling.git,gitcafe-pages

deploy:
  type: rsync
  host: codefalling.com
  user: root
  root: /var/www/blog
  port: 27137
  delete: true # Default is true
  verbose: true # Default is true
  #ignore_errors: [true|false] # Default is false


feed:
  type: atom
  path: atom.xml

sitemap:
    path: sitemap.xml

org:
    common: |
            #+OPTIONS: toc:nil
            #+BEGIN_HTML
              <script>
                function editAtGithub(isRaw){
                  var url_parts = document.location.pathname.split('/');
                  var postname = url_parts[url_parts.length - 2];
                  if(url_parts.length == 3){ // is a page(wiki about etc)
                    postname = postname + '/index.org';
                  }else{
                    postname = '_posts/' + postname + '.org';
                  }

                  var url = 'https://github.com/CodeFalling/codefalling.github.io/tree/source/source/' + postname;
                  if(isRaw)
                    url = 'https://raw.githubusercontent.com/CodeFalling/codefalling.github.io/source/source/' + postname;
                  window.open(url);
                }
              </script>
            #+END_HTML
            #+BIND: org-html-postamble \"<a href='javascript: editAtGithub();'>Edit Me at Github</a> - <a href='javascript: editAtGithub(true)'>Org Source</a> - Last Updated %d.</br>Render by <a href='https://github.com/CodeFalling/hexo-renderer-org'>hexo-renderer-org</a> with %c\"

# Theme

avatar: https://avatars3.githubusercontent.com/u/5436704?v=3&s=460

disqus_shortname: codefalling

social:
  GitHub: https://github.com/codefalling
  Twitter: https://twitter.com/codefalling
  ZhiHu: https://www.zhihu.com/people/falling-70

theme_config:
  # head
  menu:
    Home: /
    Archives: /archives
  rss: /atom.xml
  favicon: /favicon.png
  
  # main
  date_format: 'MMMM D, YYYY'
  excerpt_link: READ MORE
  comment_link: 0 COMMENTS
  
  # foot
  # themes_mata: '❤ Theme by <a href="http://unmric.com"target="_blank">unmric</a>'
  google_analytics: UA-72449503-1
  
